### ISSUE TITLE
Windows from certain applications (e.g. IntelliJ IDEA) end up in the windowList in GetOpenWindowsWithTheSameNameAsTheCurrentProcess even when it's a different process

### ISSUE THREAD

**Issue by surkh** [marcosdiez/alt_tab_helper#1]
Thank you for creating a great tool!  I was also looking to make something very much along these lines because I too wanted this specific subset of features from VistaSwitcher while still using the native Windows 10 Alt+Tab experience.

I found this bug, and I think it happens when there are Java based apps running alongside.

I will be creating a pull request shortly for a possible, short-term, partial fix for the issue.

**Comment by marcosdiez** [comment]
Thanks for sending #2 , which fixes this!
